# Help
# - https://help.github.com/en/articles/configuring-jekyll
# - https://jekyllrb.com/docs/configuration/default/
# - https://jekyllrb.com/docs/configuration/front-matter-defaults/

# Unset default theme 'jekyll-theme-primer'
theme: null

# Don't copy these files to _site/
exclude:
    - CNAME
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md 

# Show posts from the future
future: true

# Set default layout for posts
defaults:
  -
    scope:
        path: "_posts"
    values:
        layout: "post"
